// JavaScript Document

	function ConfirmExit() {
		document.getElementById("Outer2").style.display = "block"
		document.getElementById("Outer").style.display = "none";
		document.getElementById("Outer4").style.display = "none";
		document.getElementById("Outer3").style.display = "none";;
		MSApp.terminateApp();
	/*	alert('backbutton');*/
		 }

function todaysDate() {
var d = new Date();
document.getElementById("demo").innerHTML = d.toDateString();
}

function myFunction() {
	document.getElementById('Outer').style.display = 'none';
	document.getElementById('Outer2').style.display = 'block';
	document.getElementById('Outer3').style.display = 'none';
	document.getElementById('Outer4').style.display = 'none';
	document.getElementById('Texty').innerHTML='Today\'s Quote';		
/*var now = new Date();
var start = new Date(now.getFullYear(), 0, 0);
var diff = now - start;
var oneDay = 1000 * 60 * 60 * 24;
var day = Math.floor(diff / oneDay);
alert(day);*/

}

function backFunction(){
if (select==1) {
  // alert("came from homepage");
   document.getElementById('Outer2').style.display = 'block';document.getElementById('Outer3').style.display = 'none';document.getElementById('Outer4').style.display = 'none'; document.getElementById('Outer').style.display = 'none';
} else {
    //alert("came from quotespage");
	  document.getElementById('Outer').style.display = 'block';document.getElementById('Outer3').style.display = 'none';document.getElementById('Outer4').style.display = 'none'; document.getElementById('Outer2').style.display = 'none';
}
}
//var Texty = document.getElementById("textDiv");
var select = 1;
var now = new Date();
var start = new Date(now.getFullYear(), 0, 0);
var diff = now - start;
var oneDay = 1000 * 60 * 60 * 24;
var day = Math.floor(diff / oneDay);
var car=[];
car[0]="Happy New Year! Now get your ass on that saddle and go for a bike ride to work off the festive excess!";
car[1]="Happy New Year! Now get your ass on that saddle and go for a bike ride to work off the festive excess!";
car[2]="The January sales are an ideal time to buy a brand new bike and / or cycling kit, bargains are to be had both on and offline.";
car[3]="\"I sat in those chairs before the 500m and thought, 'I'm going to win'. That was just my attitude. And I've definitely still got it.\"<br><br><div class=\"SigText\">- Laura Trott</div>";
car[4]="When riding on gritted and salted roads during winter, it is important to wash your bike as soon as possible, otherwise you may find rust forming.";
car[5]="Winter miles summer smiles.";
car[6]="\"Everytime I see an adult on a bicycle I no longer dispair for the human race.\"<br><br><div class=\"SigText\">- H.G. Wells</div>";
car[7]="Keep calm and ride on...";
car[8]="Bike to work, bike to play, bike tomorrow, bike today.";
car[9]="Practice changing your inner tubes in your spare time, that way if you acquire a puncture on the road/trail you will know exactly what to do.";
car[10]="The first incarnation of the bicycle was the walking machine invented in 1817 by Baron von Draisby. The machine became known as the Draisienne or hobby horse and was made entirely of wood.";
car[11]="How many layers do I need to wear during Winter? Aim to be slightly cold when setting out. The first few minutes may feel chilly, but your body produces a vast amount of heat when riding a bicycle so you'll warm up quickly.";
car[12]="\"There’s no F**King drug in the world that could give you a high like that.\"<br><br><div class=\"SigText\">- Shaun Palmer</div>";
car[13]="Note down your bicycle serial number which is visually stamped on the frame underneath the bottom backet. This will help police to identify your bike if it ever got stolen and recovered. There are also a number of websites for registering your serial number such as www.bikeregister.com";
car[14]="\"You’ll likely have to change the saddle your bike came with. You shouldn’t be thinking about your saddle when you ride, if it’s uncomfortable it’s time to change it.\"";
car[15]="\"When man invented the bicycle he reached the peak of his attainments.\"<br><br><div class=\"SigText\">- Elizabeth West, US author</div>";
car[16]="Try wrapping tin foil over your socks (front of feet area) for added insulation during the winter period.";
car[17]="\"The finest mode of transport known to man.\"<br><br><div class=\"SigText\">- Adam Hart-Davis</div>";
car[18]="Cheap and basic DIY energy drink recipe - 70% water, 30% orange juice, small amount of sugar to your energy and taste needs, pinch of salt.";
car[19]="Porridge is ideal fuel before heading out on the road or trail, throw in some fruit such as strawberries, banana or blueberries for added taste.";
car[20]="What is the Lantern Rouge? The Lantern Rouge is the competitor in last place in a cycling race such as the Tour de France. The phrase comes from the French \"Red Lantern\" and refers to the red lantern hung on the caboose of a railway train, which conductors would look for in order to make sure none of the couplings had become disconnected.";
car[21]="\"Life is like riding a bicycle. To keep your balance, you must keep moving forward.\"<br><br><div class=\"SigText\">- Albert Einstein</div>";
car[22]="Joke:<br><br>A cyclist lying on his deathbed asked his best friend to do him a favour when he’d gone. \"Anything,\" replied his friend. \"Just don’t let my wife sell my bikes for what I told her I paid for them.\" he begged.";
car[23]="A glass of milk or a milkshake are reportedly just as good as a more dedicated recovery drink.";
car[24]="Everybody is different and a comfortable saddle is a personal thing. A decent bike shop will have a measuring pad to help choose the best size saddle for you. You may need to try out a few saddles before you find the one that suits you.";
car[25]="Water Bottles: Use a bottle with a protective flip top cover to avoid mud splashing onto the drinking spout.";
car[26]="Just because it's Winter or the weather is bad it doesn't mean you have to stop riding your bike... investing in a turbo trainer or rollers will keep you fit and see you through.";
car[27]="Cycling isn't a hobby for me... it's my INNER PEACE!";
car[28]="\"Cyclists see considerably more of this beautiful world than any other class of citizens. A good bicycle, well applied, will cure most ills this flesh is heir to.\"<br><br><div class=\"SigText\">- Dr K.K. Doty</div>";
car[29]="How to Improve your year:<br>Step 1. Ride your bike.<br>Step 2. Repeat step 1 for 365 days...";
car[30]="\"Always use lights.\"<br><br><div class=\"SigText\">- Brad Collard</div>";
car[31]="\"I used to work in a bank when I was younger and to me it doesn’t matter whether it’s raining or the sun is shining or whatever: as long as I’m riding a bike I know I’m the luckiest guy in the world.\"<br><br><div class=\"SigText\">- Pro racer Mark Cavendish</div>";
car[32]="Accept the days when cycling feels impossible. Embrace the days when cycling feels effortless.";
car[33]="Refuel Right: The key recovery window is 30 minutes following a ride. That's when your muscles need protein to repair themselves and the body needs to reload it's energy stores. Aim to get 20 to 25 grams of protein inside you for optimum recovery.";
car[34]="Feet on the pedals... head in the clouds...";
car[35]="Joke:<br><br> Q: What do you call a crazy pavement?<br><br>A: A cycle path.";
car[36]="\"Never use your face as a brake pad.\"<br><br><div class=\"SigText\">- Jake Watson</div>";
car[37]="To keep a bottle of water from freezing on a long ride, carry it in your jersey pocket so it can absorb some warmth from your body.";
car[38]="Great minds think a bike.";
car[39]="Studies have shown that riding a bike makes you more awesome than the general population.";
car[40]="\"It's like wrestling a gorilla. You don't quit when you're tired. You quit when the gorilla is tired.\"<br><br><div class=\"SigText\">- Fausto Coppi</div>";
car[41]="Scan the rear windows of parked cars for someone who might suddenly pull out into your lane or throw open a door. You can also spot pedestrians about to step out from between cars.";
car[42]="Joke:<br><br> This oaf was riding his bike around Piccadilly, London. \"Look at that dope on a bike\" said a policeman. He then arrested him for dope pedalling.";
car[43]="\"When my legs hurt, I say; Shut up legs! Do what I tell you to do!\"<br><br><div class=\"SigText\">- Jens Voight</div>"
car[44]=" Joke:<br><br> Q: How did the barber win the bike race?<br><br>A: He took a short cut.";
car[45]="All ass no gas.";
car[46]="Joke:<br><br>\"I prefer running…\"";
car[47]="Always be there for others. Always inspire them with your dreams and hope, vision and mission, attitude and aptitude.";
car[48]="I came... I spun...<br>I CONQUERED!";
car[49]="When taking the lead position in a paceline, as the former leader drops to the back, don't accelerate. Maintain the same speed as when drafting so you don't cause gaps to open between the other riders.";
car[50]="The best invention after the wheel... was putting two of them together.";
car[51]="\"Being a cyclist is more than riding your bike... you feel it in your heart and soul.\"";
car[52]="Bike Security. Spend as much as you can afford on a bike lock. As a general rule it ideally should be 1/4 to 1/3 of how much your bike is worth. With bike locks you are generally buying the time a thief spends to take it. Gold secure rated locks are classed as most secure.";
car[53]="The first chain driven bicycle was called the rover and was first exhibited in London in early 1885 by J.K. Starley.";
car[54]="\"I'm OK, just hit my head on the lamppost, but I'm all right. The doctor asked me a few questions, my name and stuff. I said I'm Chris Froome.\"<br><br><div class=\"SigText\">- Geraint Thomas</div>";
car[55]="Switchback tip: On the turn, stay off your front brake; use the rear only if necessary. Try to do all braking before.";
car[56]="\"Training can be monotonous, and it is hard work, but you never lose sight of why you are doing it. Every single effort of every single session counts in the months and years leading up to a big event.\"<br><br><div class=\"SigText\">- Sir Chris Hoy</div>";
car[57]=" If you need to change direction or position on the road, always look first to check it's safe to do so and then, where applicable, make a clear signal to alert other road users / pedestrians of your intended action.";
car[58]="\"When you legs scream and your lungs stop and your legs are bursting, that's when it starts. That's the hurt locker. Winners love it in there.\"<br><br><div class=\"SigText\">- Chris McCormack</div>";
car[59]="\"While climbing, don’t go too hard too early on and ensure you continue to pedal over the top of the climb. Often cyclists stop pedalling at what they perceive to be the top only to lose momentum when they are several feet from the plateau.\"<br><br><div class=\"SigText\">- Tim Hoyle</div>";
car[60]="Weather forcast can be broken down into 2 categories... good biking weather, bad biking weather.";
car[61]="Clicks during out-of-saddle climbing and sprinting sometimes come from two spokes rubbing. Put a drop of oil on each spoke intersection.";
car[62]="There are plenty of tutorial videos on youtube for learning simple bike maintenance - for example how to clean your chain or how to change a gear cable and tune gears.";
car[63]="\"If your day job keeps you from riding as much as you'd like, you aren't as fast as you think you are.\"<br><br><div class=\"SigText\">- Knolly Bikes</div>";
car[64]="\"Melancholy is incompatible with bicycling.\"<br><br><div class=\"SigText\">- James E. Starrs</div>";
car[65]="Don't just look at your kit... RIDE IT!";
car[66]="Only a cyclist knows why a dog sticks his head out of the car window.";
car[67]="Mountain Biking Downhill: Shifting into the big chainring before a bumpy descent will help keep the chain from bouncing off, and should you crash or disengage your leg from the pedal, the chain will cover the teeth of the big ring so they don't bite into your leg.";
car[68]="\"Never take what one bike shop says as your size as gospel for all bike brands. I spend half my life trying to explain to people that a 48cm in Cannondale is like a 51cm in Cervelo.\"<br><br><div class=\"SigText\">- Bryan Hutton<div>";
car[69]="\"Don’t be afraid to wear Lycra. It’s odd at first but, trust me, it’s the most comfortable way to ride.\"<br><br><div class=\"SigText\">- Keith Russell</div>";
car[70]="When you cast a crisp shadow on the road, take the opportunity to check your position - are your elbows bent, back flat, knees slightly bent at the bottom of the pedal stroke, head up without being torqued at the neck?";
car[71]="\"It may seem odd that cycling (often) seems to be less about riding than it is about getting the ride over with as soon as possible... enjoyable things should be savoured... racing a century is the cycling equivalent of shotgunning a beer. Eventually you learn that sipping is more enjoyable - and it gets you just as drunk in the end.\"<br><br><div class=\"SigText\">– The Bike Snob, Bicycling, October 2009</div>";
car[72]="Accelerate over the top of hills. A lot of riders relax and slow down as they get to the top of a hill climb, PUSH ON! (The downhill will come soon enough)";
car[73]="I totally regret that sweaty calorie burning bike ride around the lake while watching men cycle in tight shorts - said no woman ever!";
car[74]="Joke:<br><br>Q: When is a bicycle not a bicycle?<br><br>A: When it turns into a driveway.";
car[75]="Want to Ride Faster? Join a club - riding and keeping up with other people of similar fitness will soon progress your fitness to the next level.";
car[76]="Carry an emergency bike lock even if you don't intent to stop, one day you may get caught out and will need to quickly pop into a shop, cafe, or toilet.";
car[77]="If you hear a metallic click during every crank revolution, grease the pedal threads (and tighten firmly when reinstalling).";
car[78]="Break up long rides with a 15-second sprint every 30 minutes or so—adding variety to a monotonous pace is better training, relieves saddle pressure, and stretches and relaxes your body.";
car[79]="Life sucks and then... you bike!";
car[80]="\"Shut Up Legs. Do What I Tell You To Do!\"<br><br><div class=\"SigText\">– Jens Voigt</div>";
car[81]="Two easy (and most overlooked) ways to improve your bike's performance: Inflate the tires before every ride, and keep the chain lubed.";
car[82]="The Bicycle, the simple solution to some of the world's most complicated problems.";
car[83]="Mountain Biking: When mountain biking downhill, try not to use the front brake only as you could end up going over the handlebars.";
car[84]="Buzzing occurs when a cage, frame pump, or some other add-on vibrates, or when a cable housing quivers against the frame. To find the culprit, touch these areas while riding, then tighten, shorten, reroute, or tape as necessary.";
car[85]="\"Bike riding is a way to explore… a way to explore nature and the world.\"<br><br><div class=\"SigText\">– Cam Zink</div>";
car[86]="Commuting:<br>If there are no showers available at your work place consider carrying some baby wipes to clean yourself in the bathroom.";
car[87]="Icky but effective: If you're going to be doing a lot of riding in cold, windy weather, don't clean your ears as often as usual. Removing the wax makes earaches more likely, because it exposes the inner ear to rushing air.";
car[88]="\"Get a professional bike fit when you buy your bike and revisit your fit every season. As a bodyworker, I see a lot of problems that are only exacerbated by an ill-fitting bicycle.\"<br><br><div class=\"SigText\">- Nick Boyle</div>";
car[89]="\"First week you feel good, the second week you lose strength. Third week, F***ed.\"<br><br><div class=\"SigText\">- Per Pedersen, on the Tour de France</div>";
car[90]="Ride well into the lane when traffic is stop-and-go. You can usually move at least as fast as cars in heavy traffic, and if you hug the curb, you're less visible and drivers will be tempted to squeeze by you.";
car[91]="Cycling...<br>put the fun between your legs!";
car[92]="Don't move your upper body too much. Let your back serve as a fulcrum, with your bike swaying from side to side beneath it.";
car[93]="\"Like dogs, bicycles are social catalysts that attract a superior category of people.\"<br><br><div class=\"SigText\">- Chip Brown</div>";
car[94]="Carbohydrate is arguably the most important source of energy for cyclists. Carbohydrate provides the energy that fuels muscle contractions. Ideal food containing carbohydrates are breads, rice and pasta.";
car[95]="On descents, your bike is much more stable when you're pedaling than when you're coasting.";
car[96]="Bicycles: The mobile device that charges you!";
car[97]="Maintenance. To Prevent risk of your chain snapping on the road / trail it is recommended to change it every 2000 miles. This will also help maintain your cassette for longer.";
car[98]="Crash Avoidance: When riding in a group do not overlap wheels. To some degree there will always be an overlapping of wheels but it is a bad position to put yourself in.";
car[99]="\"If it’s hurting me, it’s killing them.\"<br><br><div class=\"SigText\">- Sebastian Kienle, on setting the pace for his competition during the bike leg of the Ironman World Championship.</div>";
car[100]="When was mountain biking invented? Early bicycles were always ridden off road as well as on - however, the first incarnations of the modern day mountain bike originated on California in the 1970's.";
car[101]="I don't ride a bike to add days to my life, I ride a bike to add life to my days.";
car[102]="\"Give a man a fish and feed him for a day. Teach a man to fish and feed him for a lifetime. Teach a man to cycle and he will realize fishing is stupid and boring.\"<br><br><div class=\"SigText\">- Desmond Tutu</div>";
car[103]="After you grab your water bottle, don't tilt your head to drink. Tilt the bottle and squeeze the water in. You'll have more control."
car[104]="Eat predictably on event day. Never eat anything new on event day - you don't want to end up with an upset stomach. Training days are for experimenting with.";
car[105]="Your bike says alot about you. This one says \"I like bikes\".";
car[106]="\"Ride are much or as little as you feel, but ride.\"<br><br><div class=\"SigText\">- Eddie Merckx</div>";
car[107]="\"Think of bicycles as ridable art that can just about save the world.\"<br><br><div class=\"SigText\">- Grant Petersen, bicycle designer</div>";
car[108]="\"Downhill mountain biking, more additive than crack cocaine, and twice as expensive.\"<br><br><div class=\"SigText\">- Pinkbike.com</div>";
car[109]="You can't be sad while riding a bicycle.";
car[110]="Dont worry, bike happy.";
car[111]="\"That's the closest I'll ever come to knowing what it's like to have a baby. It was just torture.\"<br><br><div class=\"SigText\">- Sir Bradley Wiggins</div>";
car[112]="The Penny Farthing was invented in the 1870's by British engineer, James Starley.";
car[113]="Work to eat. Eat to live. Live to bike. Bike to work.";
car[114]="To avoid muscle soreness and fatigue, don't hunch your shoulders. Tilt your head every few minutes to stave off tight neck muscles. Better yet: Stop to admire the scenery.";
car[115]="Life is short... buy the damn bicycle!";
car[116]="\"When the spirits are low, when the day appears dark, when work becomes monotonous, when hope hardly seems worth having, just mount a bicycle and go out for a spin down the road, without thought on anything but the ride you are taking.\"<br><br><div class=\"SigText\">– Arthur Conan Doyle</div>";
car[117]="\"On the nutritional side, generally stick to water for rides under an hour. Carbs on rides of 1-3 hours and a mixture of carbs and protein for rides longer than 3 hours. It’s worth noting however that these are only guidelines, as nutrition is often a matter of ‘what works for you’.\"<br><br><div class=\"SigText\">- Tim Hoyle</div>";
car[118]="Always try to look well ahead down the road and anticipate any potential obstructions or dangers - so you do not have to swerve suddenly to avoid them.";
car[119]="\"Don't buy upgrades... ride up grades!\"<br><br><div class=\"SigText\">- Eddie Merckx</div>";
car[120]="It's not what you ride but that your ride. It's not how fast you go it's about enjoying the ride. It's not when you started riding but continuing to ride each day.";
car[121]="As your effort becomes harder, increase the force of your breaths rather than the frequency.";
car[122]="\"Use mudguards. It will keep you, your bike and the cyclist behind you clean.\"<br><br><div class=\"SigText\">- Stuart Barrington</div>";
car[123]="\"There is nothing, absolutely nothing, quite so worthwhile as simply messing about on bicycles.\"<br><br><div class=\"SigText\">- Tom Kunich</div>";
car[124]="Pull on the bar with a rowing motion to counter the power of your legs. This helps transfer your energy to the pedals rather than into wasted movement.";
car[125]="When anybody mentions distance you immediately think of how long it would take to cycle it.";
car[126]="\"May your trails be crooked, winding, dangerous, leading to the most amazing view. May your mountains rise into and above the clouds.\"<br><br><div class=\"SigText\">- Edward Abbey</div>";
car[127]="\"The secret to mountain biking is pretty simple. The slower you go the more likely it is you'll crash.\"<br><br><div class=\"SigText\">- Julie Furtado</div>";
car[128]="Best Budget Road Bike? The B'twin Triban 3 or Triban 5 available from Decathlon are reportedly two of the best budget road bikes.";
car[129]="\"My beginner cycling tips would be, don’t be afraid to step up a level or distance. If you are used to riding 30 miles at 15mph average, go out with others on a 40 mile at 16-17 average. You will surprise yourself!\"";
car[130]="Forget the glass slippers... this princess wears cycling shoes!";
car[131]="Things to love about cycling. Cycling is very low impact on your joints (such as knees) compared to other forms of sport and fitness.";
car[132]="Fed up of fiddly cable ties at events? Try using pipe cleaners to attach your entry number to your handlebars, they are easily adjusted and removed compared to standard cable ties.";
car[133]="♫ Always look on the bike side of life. ♫";
car[134]="Take Your Wrappers Home! Please consider the environment and keep the countryside clean by taking your empty gel wrappers home with you after use.";
car[135]=" Ideally you should carry a quick link and multitool with a chain splitter attached as you never know when your chain might break."
car[136]="My biggest fear is that when I die my wife will sell my bicycles for what I told her they cost.";
car[137]="The padding on tights and shorts are designed to be worn commando (no pants / knickers underneath) Try it... you might like it!";
car[138]="Mountain Biking: For super steep, technical descents, you may want to drop your saddle 2 or 3 inches. This lowers your centre of gravity, giving you more room to bounce around.";
car[139]="Commuting:<br>If you commute to work and need to change into work clothes when you get there - have some spare emergency clothes at work incase you forget to pack your daily clothes in your bag / pannier. Otherwise one day you may be spending the day working in cycling kit.";
car[140]="Psyclepath. Noun: A person suffering from an extreme love of bicycles."
car[141]="Suffer from insomnia? Go for a bike ride! Stanford University School of Medicine researchers asked sedentary insomnia sufferers to cycle around 20 - 30 minutes a day. The result? The time required for insomniacs to fall asleep was reduced by half, and sleep time increased by almost a hour.";
car[142]="Cycling just 20 miles a week reduces your risk of heart disease to less than half of those who take no exercise.";
car[143]="\"It doesn’t matter if you’re sprinting for an Olympic gold medal, a town sign, a trailhead, or the rest stop with the homemade brownies. If you never confront pain, you’re missing the essence of the sport.\"<br><br><div class=\"SigText\">– Scott Martin</div>"
car[144]="If you're caught out riding and find that you're getting too cold or need a windbreaker, get a newspaper and insert sections of it inside your cycling jersey, it will act as a temporary windbreaker and insulator.";
car[145]="Struggling to open your bars / gels / jelly babies? Partly cut the tops before starting to ride for easy access whilst on the bike.";
car[146]="\"The slower you go the more likely it is you’ll crash.\"<br><br><div class=\"SigText\">- Juli Furtado</div>";
car[147]="\"Cycling has encountered more enemies than any other form of exercise.\"<br><br><div class=\"SigText\">- 19th century author Louis Baudry de Saunier</div>";
car[148]="If someone tells you that you have enough bicycles and you don't need anymore stop talking to them... you don't need that kind of negativity in your life!"
car[149]="Mountain Biking. Keep your legs relaxed and flexible as they are the most effective shock absorbers you have.";
car[150]="An hour of cycling a day can reduce the risk of coronary heart disease by up to 50%.";
car[151]="You are not stuck in traffic.. you are traffic. Get on a bike and break free...";
car[152]="\"There is nothing, absolutely nothing, quite so worthwhile as simply messing about on bicycles.\"<br><br><div class=\"SigText\">– Tom Kunich</div>";
car[153]="\"Never ignore your instinct and you can always push harder. I get inspired when I think about people who have pushed their bodies to the limit.\"<br><br><div class=\"SigText\">– Rachel Atherton</div>";
car[154]="I have too many bikes... said no cyclist ever!";
car[155]="Life's a climb, but the view is great!";
car[156]="Keep your arms in line with your body, not splayed elbows out. This is an easy way to make yourself more aerodynamic and go faster with no extra energy."
car[157]="Cycling Glasses: Wear your cycling glasses over your helmet straps - that way, if you are ever in an accident they will fly off easily and not get caught up in the helmet which could potentially cause more damage to yourself.";
car[158]="Cycling on a budget in the UK? Look out for Aldi and Lidl's 'Cycling Special Offers' which occur twice a year.";
car[159]="If you see me collapse... pause my Garmin.";
car[160]="Get more life from your tires by switching them from one wheel to another. The rear wears more than twice as fast as the front, so swapping every 500 miles or so significantly extends their longevity.";
car[161]="When riding one-handed on a drop bar bike, grip the bar on top next to the stem. If your hand is farther out (such as on the brake-lever hood), the bike is more likely to veer dangerously should the front wheel hit a rock, bump, or pothole.";
car[162]="After adjustments to your saddle position, handlebar height, stem length, or cleat placement, minor discomfort is normal as your body adapts to the changes. Resist the temptation to fiddle again after just one short ride.";
car[163]="If you're leading a paceline up a hill, keep your cadence and pedal pressure constant by shifting to a lower gear.";
car[164]="\"[Commuting by bicycle is] an absolutely essential part of my day. It’s mind-clearing, invigorating. I get to go out and pedal through the countryside in the early morning hours, and see life come back and rejuvenate every day as the sun is coming out.\"<br><br><div class=\"SigText\">- James L. Jones</div>";
car[165]="\"When the spirits are low, when the day appears dark, when work becomes monotonous, when hope hardly seems worth having, just mount a bicycle and go out for a spin down the road, without thought on anything but the ride you are taking.\"<br><br><div class=\"SigText\">- Arthur Conan Doyle</div>";
car[166]="Sometimes the open road or trail is all you need...";
car[167]="\"The bicycle has done more for the emancipation of women than anything else in the world.\"<br><br><div class=\"SigText\">- Susan B. Anthony, US women's rights activist</div>";
car[168]="Joke:<br><br>Q: What’s the hardest part of learning to ride a bike?<br><br>A: The road.";
car[169]="Commuting. If you can, leave your bike lock(s) at work to save carrying it to and fro every day.";
car[170]="Over a period of time every chain will stretch resulting in poor shifting and the high possibility of the chain snapping. A chain wear indicator will help determine if your chain needs to be replaced.";
car[171]="Basic saddlebag checklist: Spare innertube, puncture kit / self adhesive patches, tyre levers, multitool, rear light.";
car[172]="Stretching on the bike helps minimize fatigue. Coast, put your left foot down, then lean far to the right to stretch your back and your left leg. Then do the right leg.";
car[173]="\"I never met anybody who regretted taking a long ride, but I've met many who regretted not doing one.\"<br><br><div class=\"SigText\">- Alistair Humphreys</div>";
car[174]="Cycling: Side effects include sweating, euphoria and general awesomeness.";
car[175]="Always ride with your elbows bent and your arms and shoulders relaxed, this prevents fatigue caused by muscle tension, it also allows your arms to absorb shock instead of transmitting it to your body.";
car[176]="If you acquire soreness in the nether region make sure the saddle is level and straight. A low handlebar can cause your pelvis to rotate forward and down, so try raising it with spacers. Finally, test seats of different widths, lengths, firmnesses, and shapes.";
car[177]="\"My biggest tip would be to ‘Just ride’. Get out, short rides, long rides, lone rides or group rides. They all count and you’ll always feel better for it! Just enjoy it!\"<br><br><div class=\"SigText\">- Donna Navarro</div>"
car[178]="\"I ride because somehow completely exhausting myself is the most relaxing part of my day.\"";
car[179]="Benefits of cycling: Scientists at Stanford University have found that cycling regularly can protect your skin against the harmful effects of UV radiation and reduce some of the signs of aging.";
car[180]="\"It’s a risky business being a cyclist in the UK, there are a lot of people who really dislike us. It’s the Jeremy Clarkson influence – we’re hated on the roads. We just hope people realise we are just flesh and bones on two wheels.\"<br><br><div class=\"SigText\">- Victoria Pendleton</div>";
car[181]="\"In sport you always think the strongest guy should be going for it and getting the best results. The thing is, cycling also has a very important team aspect, which I don't think that a lot of people fully grasp.\"<br><br><div class=\"SigText\">- Chris Froome</div>";
car[182]="\"A bad day on the mountain bike always beats a good day in the office.\"<br><br><div class=\"SigText\">- Mike Brcic</div>";
car[183]="\"Make use of your gears (and wear out your shifters) by changing frequently to avoid ‘grinding the pedals’ on both flats and climbs. Cadence is also a personal preference, but I’d generally say 90-110rpm on flats/descents and around 70-90rpm on climbs.\"<br><br><div class=\"SigText\">- Tim Hoyle</div>";
car[184]="\"Bicycles are the indicator species of a community, like shellfish in a bay.\"<br><br><div class=\"SigText\"> - P. Martin Scott</div>";
car[185]="Cycling... cheaper than therapy.";
car[186]="If she chooses a day on the bike over a day of shopping... then you got yourself a keeper.";
car[187]="When in doubt, pedal it out.";
car[188]=" If you live in the UK, Consider joining British Cycling, benefits include: up to £10m liability insurance, Free legal advice and support for cycling incidents, 10% off at Halfords, including the Boardman Range, weekly email newsletters, plus much more. www.britishcycling.org.uk";
car[189]="It is better to carry a little more fuel than you think you will need rather than to run out of energy and bonk!";
car[190]="Things to love about cycling... the rewarding freewheeling downhill after you have huffed and puffed uphill.";
car[191]="ICE (In Case of Emergency) Put your emergency contacts on your mobile under ICE so that the police / ambulance / rescue services know who to call if you are ever involved in an accident.";
car[192]="\"If I can bicycle, bicycle.\"<br><br><div class=\"SigText\">- Sir David Attenborough</div>";
car[193]="Consider joining a breakdown recovery service such as Cycleguard Recovery (www.cycleguard.co.uk) who will rescue you if you have a breakdown over 1 mile away from home.";
car[194]="\"Cycling is much more fun than dating... I still get to chase women, and sometimes catch them. But when I get dropped, at least there is no emotional attachment.\"<br><br><div class=\"SigText\">– T. A. Melton</div>";
car[195]="\"You either love spinning the pedals and watching scenery whiz by, or you don’t. And if you love it, not much can sour you on the idea of riding your bike.\"<br><br><div class=\"SigText\">- Keith Mills</div>";
car[196]="\"It really is all about believing in yourself. 80% mental, 20% physical.\"<br><br><div class=\"SigText\">– Victoria Pendleton</div>";
car[197]="Slow and fast twitch muscle fibres. Every muscle is made up of two types of fibres. Fast-twitch fibres move 2 to 3 times faster than slow-twitch fibres, but they tire more easily. Fast-twitch fibres, logically, are used for sprinting and quick ascents. Inversely, slow-twitch fibres are used for long rides of moderate intensity.";
car[198]="No hose? If you don't have easy access to a hose when washing your bike consider buying a garden sprayer. A 3 to 6 litre sprayer will do the job and doesn't cost the earth.";
car[199]="Free your mind... just pedal and your legs will follow.";
car[200]="The safest headlight setup for night riding: one that aims its beam somewhat downward (and far enough ahead to let you ride as fast as you want while being able to see and react to changing conditions in time), with a second light at the eye level of motorists, to catch their attention.";
car[201]="\"Riding bicycles will not only benefit the individual doing it, but the world at large.\"<br><br><div class=\"SigText\">- Udo E. Simonis</div>";
car[202]="Ride a door's width space when passing parked cars. You never know when a door will randomly open because the driver / passenger isn't paying attention to what is around them.";
car[203]="\"If you have no friends that cycle, join a local club. You will soon make friends, enjoy the group riding and soon improve performance levels.\"<br><br><div class=\"SigText\">- Keith Russell</div>";
car[204]="Thumping is usually felt as much as heard. Common causes: dented rims and bulging or improperly seated tires.";
car[205]="\"Meet the future; the future mode of transportation for this weary Western world. Now I’m not gonna make a lot of extravagant claims for this little machine. Sure, it’ll change your whole life for the better, but that’s all.\"<br><br><div class=\"SigText\">- Bicycle salesman in Butch Cassidy and the Sundance Kid, 1969</div>";
car[206]="\"If constellations had been named in the 20th century, I suppose we would see bicycles.\"<br><br><div class=\"SigText\">- Professor Carl Sagan, US scientist</div>";
car[207]="Joke:<br><br>Q: Why can’t elephants ride bikes?<br><br>A: They don’t have thumbs to ring the bell.";
car[208]="To get safely through a sandy or gravel-strewn turn, straighten your bike until you're past the loose stuff, then resume turning. Avoid braking or excessively leaning while on a loose surface. Shift your weight back to help the bike track straight.";
car[209]="\"Cycling isn’t a game, it’s a sport. Tough, hard and unpitying, and it requires great sacrifices. One plays football, or tennis, or hockey. One doesn’t play at cycling.\"<br><br><div class=\"SigText\">- Jean de Gribaldy</div>";
car[210]="It's just a hill... GET OVER IT!";
car[211]="\"The bicycle is a curious vehicle, it's passenger is it's engine.\"<br><br><div class=\"SigText\">- Jon Howard</div>";
car[212]="\"Wear an additional light on your helmet. When behind a car your lights are obscured from cars joining from side roads. At least they will see the light on top of your head.\"<br><br><div class=\"SigText\">- Stuart Barrington</div>";
car[213]="\"Use Youtube videos to learn about bike maintenance. Cheaper than a course, and loads of information available.\"<br><br><div class=\"SigText\">- Stuart Barrington</div>";
car[214]="We ride... to fly, to breath, to touch, to feel beautiful, to laugh, to soar, to relax, to belong, to feel strong, to overcome, to heal, to prove them wrong, to feel free... TO LIVE!";
car[215]="\"The bicycle, the bicycle surely, should always be the vehicle of novelists and poets.\"<br><br><div class=\"SigText\">- Christopher Morly</div>";
car[216]="\"A good quote is like a handle of the bicycle which has the power to take you into the beautiful path of life.\"<br><br><div class=\"SigText\">- Vikrant Parsal</div>";
car[217]="\"Always smile, nod or say hello to passing cyclists.\"<br><br><div class=\"SigText\">- Keith Russell</div>";
car[218]="Things to enjoy about cycling... eating cake guilt free at the cafe stop.";
car[219]="\"Life is better on a mountain bike.\"<br><br><div class=\"SigText\">- Sacred Rides motto</div>";
car[220]="\"When I first started out in [Mountain Biking], it was all about having fun, playing with my mates, with a bit of racing thrown in. Nothing has changed!\"<br><br><div class=\"SigText\">- Steve Peat</div>";
car[221]="When you stop at a light, move to the centre of your lane. This prevents drivers from edging forward, trapping you between them and the curb. When the light changes, accelerate to your cruising speed before moving right to allow them to pass.";
car[222]="\"Mountain Biking:<br>The under-rated and drug-free antidepressant.\"<br><br><div class=\"SigText\">- betterride.net</div>";
car[223]="If you have numb hands you are probably putting too much weight on your hands. Raise your handlebar or shorten your stem (or both). Also check the saddle - if it angles down, you could be tilting / sliding toward the handlebars.";
car[224]="Bicycles may change, but cycling is timeless.\"<br><br><div class=\"SigText\">- Zapata Espinoza</div>";
car[225]="\"Bicycling is the nearest approximation I know to a flight of birds.\"<br><br><div class=\"SigText\">- Louis J. Helle Jr</div>";
car[226]="\"Pain is still the friend that always tells me the truth.\"<br><br><div class=\"SigText\">– Chris Froome</div>"
car[227]="\"Nothing compares to getting your heart rate up to 170-something, riding hard for an hour-twenty, getting off and not hurting, as opposed to 24 minutes of running, at the end of which I hurt. When you ride a bike and you get your heart rate up and you’re out, after 30 or 40 minutes your mind tends to expand; it tends to relax.\"<br><br><div class=\"SigText\">- [Former] President George Bush</div>";
car[228]="\"Truly, the bicycle is the most influential piece of product design ever.\"<br><br><div class=\"SigText\">- Hugh Pearman</div>";
car[229]="Training for long distance rides. Build up your distances bit by bit to avoid injury. For example: Get comfortable with riding 20 miles before trying a 40 mile ride, you will be suprised how quickly your fitness and stamina improves.";
car[230]="Whenever you make the transition from standing to sitting, gain a few free inches by pushing the bike forward as you drop to the saddle.";
car[231]="\"You never have the wind with you - either it is against you or you're having a good day.\"<br><br><div class=\"SigText\">- Daniel Behrman</div>";
car[232]="Joke:<br><br>Girl talking about this boy she just met: \"He told me he had a great bike, but then i saw it was a Trek...\"";
car[233]="\"As long as I breathe, I attack.\"<br><br><div class=\"SigText\">- Bernard Hinault, French cyclist</div>";
car[234]="Don't forget to charge your cycling computer before heading out, especially if you are using it for navigation.";
car[235]="Over time, bacteria can form inside your water bottles. To prevent this pop them into the freezer - this will kill any bacteria which may be forming.";
car[236]="Things to love about cycling... it gives you great legs!";
car[237]="More biking, more music... less people, less bullshit.";
car[238]="\"It is the unknown around the corner that turns my wheels.\"<br><br><div class=\"SigText\">- Heinz Stucke</div>";
car[239]="\"One thing that cycling has taught me is that if you achieve something without a struggle it’s not going to be satisfying.\"<br><br><div class=\"SigText\">- Greg LeMond</div>";
car[240]="\"I don't have a bucket list but my bikeit list is a mile long.\"";
car[241]="Joke:<br><br> \"I’ve really had it with my dog: he’ll chase anyone on a bicycle.\", \"So what are you going to do - leave him at the dog’s home? Give him away? Sell him?\", \"No, nothing that drastic. I think I’ll just confiscate his bike.\"";
car[242]="\"The race is won by the rider who can suffer the most.\"<br><br><div class=\"SigText\">- Eddy Merckx</div>";
car[243]="Cycling... cheaper than therapy.";
car[244]="Saddle Creaking? Try dropping a small amount of oil around the rails where they enter the saddle and into the clamp where it grips the rails.";
car[245]="\"Good cycling clothing is the best investment you can make. Don’t waste money on an expensive fancy helmet as they all meet the same safety standard. Spend your money on decent bib shorts as they make all the difference.\"<br><br><div class=\"SigText\">- Cliff Brown</div>";
car[246]="Be vigilant for black ice when the temperatures plummet, even if it is above freezing point there may still be ice patches on roads / trails with shaded cover from the sun.";
car[247]="Joke:<br><br>Driving one winter’s day, I spotted my mate chest-high in snow. I shouted to offer him a lift but he said: \"no thanks, I’m on the bike.\"";
car[248]="\"In wet weather, keep your bike as upright as possible in corners and break earlier than usual. Also watch out for slippery oil / diesel patches which are particularly bad during the first rains of the season as well as at intersections.\"<br><br><div class=\"SigText\">- Tim Hoyle</div>";
car[249]="\"If you’re planning for wet weather riding invest in a decent pair of overshoes first. If you don’t enjoy riding in the wet an expensive pair of winter shoes will end up in not being used so a waste of money.\"<br><br><div class=\"SigText\">- Stuart Barrington</div>";
car[250]="Ride Predictively. Hold your line and position in the road. Do not weave from side to side.";
car[251]="Take one hand off the bar and shake it occasionally to prevent numbness, relax your shoulders / elbows and encourage blood flow to your hands.";
car[252]="\"A mountain bike is like your buddy. A road bike is your lover.\"<br><br><div class=\"SigText\">– Sean Coffey</div>";
car[253]="It doesn't matter what age you are, what size you are, how fit you are, the colour of your skin, CYCLING IS A SPORT FOR EVERYONE!";
car[254]="Rest Properly: You only get faster when you have rested after hard training. It is when the body is resting and recovering that it creates the adaptions to bounce back stronger.";
car[255]="\"It’s rude to count people as you pass them, out loud.\"";
car[256]="\"Don’t avoid the hills, they get easier the more you do, you can’t avoid them forever so you may as well get better at them. Good technique works on small hills, strength and fitness is more important on long slogs like the Alps.\"<br><br><div class=\"SigText\">- Mark Cockshoot</div>";
car[257]=" \"Cadence is really important. Set an alarm on your computer for when cadence drops below 80rpm, meaning it’s time to drop a gear. Eventually it becomes second nature.\"<br><br><div class=\"SigText\">- Bryan Hutton</div>";
car[258]="DIY Banana and Peanut Butter Recovery Shake.<br><br>Ingredients:<br>30ml milk<br>1 tbsp peanut butter<br>1 Banana<br>1 Scoop whey protein powder.<br><br>In a blender combine all ingredients, mix well until smooth. Add ice cubes for thicker consistency.";
car[259]="\"Any day I’m out on a bike is a good one.\"<br><br><div class=\"SigText\">– Martyn Ashton</div>";
car[260]="\"An engineer designing from scratch could hardly concoct a better device to unclog modern roads - cheap, non-polluting, small and silent…\"<br><br><div class=\"SigText\">- Rick Smith</div>";
car[261]="No gas, no traffic, free parking, pollution free, free workout... ride your bike, save the world!";
car[262]="Joke:<br><br>A vicar was stopped by the police at night for not having a back light. The vicar says: \"I don’t need a back light, the Lord is with me\". The policeman says: \"Two on a bike as well, that’s another offence.\"";
car[263]="\"If it weren’t for bicycles, world domination would be within my grasp!\"<br><br><div class=\"SigText\">– Stuart Black</div>";
car[264]="\"Until mountain biking came along, the bike scene was ruled by a small elite cadre of people who seemed allergic to enthusiasm.\"<br><br><div class=\"SigText\">- Jacquie Phelan</div>";
car[265]=" \"Are we at the cake stop yet?\"<br><br><div class=\"SigText\">- TheKay</div>";
car[266]="Cycling away from the big C. There's plenty of evidence that any exercise is usefull to warding off cancer, but some studies have shown that cycling is specifically good for keeps cells in working order.";
car[267]="What do pro riders eat / drink for fuel? A typical mussette can consist of: A selection of rice cakes, selection of gels, selection of energy bars, banana, bottle of water, bottle of energy mix.";
car[268]="Never trust your ear. Frames transmit noises. You might swear a sound is coming from your cranks, but it could be your saddle rails. Check all possible points.";
car[269]="Cycling: Get out there and discover it!";
car[270]="A chirp is almost always from the chain - it is crying out for lubrication.";
car[271]="Try not to chance your line in the middle of of corner - your front tyre could potentially wash out, especially if it's wet.";
car[272]="Joke:<br><br>Me: My friend's wife has made him give away all of his cycling stuff. I got his brakes.<br><br>Stooge: Cantilever?<br><br>Me: No, he loves her too much.";
car[273]="\"If you go (with a break), you can either win or not win. If you don’t go for it, you definitely won’t win.\"<br><br><div class=\"SigText\">- Jens Voigt</div>";
car[274]="\"Good morale in cycling comes from good legs.\"<br><br><div class=\"SigText\">- Sean Yates</div>";
car[275]="The Necessities of Life: 1 air, 2 water, 3 food, 4. my bike.";
car[276]="\"At the end of the day we're just people on bikes...\"<br><br><div class=\"SigText\">- Mike Hall, Ultra-distance Cycling Legend</div>";
car[277]="\"Be aware of the vehicles around you. When taking the inside lane, watch for indicators.\"<br><br><div class=\"SigText\">- Stuart Barrington</div>";
car[278]="\"Cycle tracks will abound in Utopia.\"<br><br><div class=\"SigText\">- H.G. Wells</div>";
car[279]="\"Nothing compares to the simple pleasure of riding a bike.\"<br><br><div class=\"SigText\">- John F. Kennedy</div>";
car[280]="Bike Security: For additional security consider a bike tagging / marking product. These tags will help the police trace you as the owner if your pride and joy ever got stolen.";
car[281]="\"At that age, it’s one of the worse things in the world to wake up and not see your bike where you left it.\"<br><br><div class=\"SigText\">- Hip-hop star 50 Cent</div>";
car[282]="\"Ride lots.\"<br><br><div class=\"SigText\">- Eddie Merckx</div>";
car[283]="\"A bicycle ride around the world begins with a single pedal stroke.\"<br><br><div class=\"SigText\">- Scott Stoll</div>";
car[284]="Setting goals for yourself such as completing your first 100km charity ride is a great motivator.";
car[285]="\"Start slowly, don’t aim to go too far or fast too soon. Build it up steadily over time and as you feel more confident and comfortable push your limits. Oh, and the most important tip of all….. Just enjoy yourself!\"<br><br><div class=\"SigText\">- Matt @mattmbr</div>";
car[286]="For inspiration, help and advice with like minded cyclists, consider looking at cyclng forums such as www.cyclechat.net or www.bikeradar.com";
car[287]="For optimal handling with 20 pounds or more of cargo, put approximately 60 percent of the weight in the rear panniers or on a rack, 35 percent on a front rack or panniers, and 5 percent in a handlebar bag.";
car[288]="\"Life may not be about your bike, but it sure can help you get through it.\"<br><br><div class=\"SigText\">- Hallman</div>";
car[289]="Always carry a bit of lose change when riding, you never know when you may need it - for example emergency train fare home or emergency food.";
car[290]="Joke:<br><br>A tandem rider is stopped by the police. \"What have I done wrong?\" says the rider.<br>\"Perhaps you didn’t notice, sir, but your wife fell off half a mile back.\"<br>\"Thank god for that,\" says the rider. \"I thought I’d gone deaf.\"";
car[291]="Research carried out by Appalacian State University shows that cycling is better than running. The researchers say runners should include cycling as part of their training, and people taking up exercise should choose cycling over running to avoid injury.";
car[292]="Go hard on climbs... and take it easy on descents.";
car[293]="Happiness is... sweet exhaustion after a hard ride.";
car[294]="\"To prepare for a race there is nothing better than a good pheasant, some champagne and a woman.\"<br><br><div class=\"SigText\">- Jacques Anquetil</div>";
car[295]="Never cycle on the inside of a lorry - it is an extremely dangerous place to put yourself in as you will most likely be in the drivers blind spot.";
car[296]="\"Bicycling is a big part of the future. It has to be. There's something wrong with a society that drives a car to workout in a gym.\"<br><br><div class=\"SigText\">- Bill Nye, US scientist</div>";
car[297]="Put your left foot down when stopping to prevent greasy chainring \"tattoos\" on your right calf.";
car[298]="Beware of creeping forward on the saddle and hunching your back when you're tired. Shift to a higher gear and stand to pedal periodically to prevent stiffness in your hips and back.";
car[299]="\"Crashing is part of cycling as crying is part of love.\"<br><br>- Johan Museeuw, Belgian cyclist";
car[300]="Cross Train: Add a bit of cross training to your schedule such as lifting weights or running. Recent studies show that cycling could be bad for bone density resulting in brittle bones. This is due to the low impact nature of cycling which doesn't put too much stress on the bones. Bones react to external stresses by strengthening bone. Weight lifters tend to have higher bone density compared to the average person.";
car[301]="Babywipes are great for cleaning / wiping down your bike.";
car[302]="If you have burning feet the simplest fix is to try riding with straps, buckles, or laces looser (but still secure). Next, move your cleats backward 2mm or less, which shifts pressure off the balls of your feet.";
car[303]="If you have knee pain in the front of your knee, raise your saddle in 2mm increments until the knee stops complaining. If the pain is in the back of your knee, lower your seat instead.";
car[304]="Did you ride your bike today?";
car[305]="Don't forget to charge your phone before heading out...";
car[306]="\"I love cycling. I am going to keep racing as hard as I can until this body doesn't allow me to any more.\"<br><br><div class=\"SigText\">- Chris Froome</div>";
car[307]="Stretching for 10 minutes after a bike ride can help aid recovery and alleviate muscle soreness.";
car[308]="Downhill Mountain biking: When mountain biking downhill, place your weight over the rear of the bike, keep your rear end as far back as possible without losing control.";
car[309]="Home baked flapjacks are very easy to make and are a cheap and popular energy food for cyclists.";
car[310]="\"The bicycle is just as good company as most husbands and, when it gets old and shabby, a woman can dispose of it and get a new one without shocking the entire community.\"<br><br><div class=\"SigText\">- Ann Strong, US writer</div>";
car[311]="Checks before each ride: Check the brakes are working ok, check wheels for brake rub, check the tyre pressures are ok, check the quick release skewers are secure, check the tyres for cuts and wear.";
car[312]="\"I'm not racing for recognition, I'm not racing for popularity, that's not who I am. I'm focused on the result and trying to get the best out of myself from a sporting capacity. That's what really motivates me.\"<br><br><div class=\"SigText\">- Chris Froome</div>";
car[313]="You're only one bike ride away from a good mood.";
car[314]=" \"Everybody had to be tired after 240km. I just ate all the gels that I had.\"<br><br><div class=\"SigText\">- Peter Sagan</div>";
car[315]=" After a cold, muddy, or gritty ride, resist the temptation to dash into the house. Instead, hose your bike while it's still wet (when it's easiest to get clean), dry any moving parts with a towel, and lube the chain. The entire process takes five to 10 minutes, and saves you at least 30 later on.";
car[316]="Pipe cleaners are great for cleaning chains cassettes and other hard to reach places on your bike.";
car[317]="\"Don’t be afraid of traffic but sit away from parked cars, at least an open door’s width. Claim your place on the road, be confident and look at drivers at junctions – they will feel your burning gaze!\"<br><br><div class=\"SigText\">- Cliff Brown</div>";
car[318]="Question:<br>Jens, what do you say to your legs?<br><br>Jens Voigt:<br>Shut up legs!";
car[319]="\"You don't quit riding your bike because you get old, you get old because you have quit riding your bike.\"<br><br><div class=\"SigText\">- Axel Reichartz</div>";
car[320]="You can't buy happiness but you can buy a bike and that's pretty damn close.";
car[321]="RIDE IT LIKE YOU STOLE IT!";
car[322]="My bike takes me places my car never will...";
car[323]="The bicycle has soul. If you succeed to love it, it will give you emotions that you will never forget.";
car[324]="You lost me at 'I don't bike'.";
car[325]="\"It never gets easier, you just go faster.\"<br><br><div class=\"SigText\">- Greg LeMond</div>";
car[326]="Be extra carefull when riding on wet roads as your tyres and easily slip. Also consider letting your tyre pressure down for extra grip.";
car[327]="Joke:<br><br>My friend rode into a tree the other day racing round his back garden. Thankfully he was able to continue, his bark was worse than his bike.";
car[328]="Keep your shoulders behind the front wheel axle. Too much weight forward makes the bike hard to handle and could cause the rear wheel to skip up into the air.";
car[329]="\"Buy the best bike you can afford, buy the best shorts you can afford.\"<br><br><div class=\"SigText\">- Brad Collard</div>";
car[330]="Cycling Apps: When using a cycling app try to start/stop your ride away from your house, this stops strangers who many be looking at your routes from finding out where you live. Alternatively have a look in your app settings to see if you can it to be viewed by yourself and friends only.";
car[331]="Rattles and jingles often come from a seat bag. Secure items with rubber bands or rags.";
car[332]="Wet chain lube is ideal for riding in rain, snow and wintry conditions.";
car[333]="Get enough sleep, shaving seconds off your ride could be as simple as spending more time sleeping.";
car[334]="Goal setting: Set yourself a goal such as signing up for a sportive or charity ride, this will help you to train better and not lose your cycling mojo.";
car[335]="When climbing, visualize pedaling across the stroke rather than simply up and down. Strive to apply power horizontally through the bottom and top of the stroke.";
car[336]="To stave off muscle fatigue during hard, sustained pedaling, learn to \"float\" each leg every three or four strokes. Simply let your foot fall without exerting force.";
car[337]="\"I was in that much pain I couldn't walk. My glutes and my groin were so cramped and damaged. I think it was the closest I could feel to death without actually dying.\"<br><br><div class=\"SigText\">- Jack Bobridge</div>";
car[338]="Relax your grip. On smooth, traffic-free pavement, practice draping your hands over the handlebar. This not only will help alleviate muscle tension, but also will reduce the amount of road vibration transmitted to your body.";
car[339]="What is the best selling bike? Mountain bikes win top spot with 25% of the market, Hybrids take second place with 24% of the market, and road bikes are in third place with 20% of the market.";
car[340]="\"Riding a bike is everything to a cyclist. The friendship and camaraderie you have with other cyclists …to a cyclist, it was the be-all and end-all of your life.\"<br><br><div class=\"SigText\">- Tommy Godwin</div>";
car[341]="Things to love about cycling... the feeling of freedom yippeeee!";
car[342]="Switchback tip: As you arrive at the turning point, look over your shoulder, in the direction you want to go. You'll be amazed how well your bike follows your head around the switchback.";
car[343]="\"If you do something right the first time, then it’s not hard enough.\"<br><br><div class=\"SigText\">- Danny MacAskill</div>";
car[344]="Honey... your can find me on my bike this weekend.";
car[345]="Hills. We love them, we hate them, they make us strong, they make us weak. Today I chose to embrace hills.";
car[346]="Cycling in hot temperatures. Make sure you're hydrated before heading out and take plenty of electrolyte drink with you on the ride, drink more than you normally would and go a little easier on your body than you usually do. Try to avoid cycling during the hottest part of the day. If you think you are suffering from heat exhaustion, go to a cool place and drink plenty of water.";
car[347]="\"Your bike is discovery; your bike is freedom. It doesn't matter where you are, when you're in the saddle, you're taken away.\"<br><br><div class=\"SigText\">- Doug Donaldson</div>";
car[348]="\"One of the most important days of my life, was when I learned to ride a bicycle.”<br><br><div class=\"SigText\">- Michael Palin</div>";
car[349]="\"Think of bicycles as ridable art that can just about save the World.\"<br><br><div class=\"SigText\">- Grant Petersen</div>";
car[350]="Joke:<br><br>Q: What do you call an artist who sculpts with bicycle parts?<br><br>A: Cycleangelo";
car[351]=" \"If I had attacked one more time I would have dropped myself.\"";
car[352]="Joke:<br><br>Since things turned sour with my wife a fortnight ago, I’ve taken to riding 50 miles a day to clear my head. I’m now 700 miles from home and feeling much happier.";
car[353]="Sometimes I wonder... if my bike is thinking about me too...";
car[354]="When riding in a group, always keep your hands in contact with your brakes, either in the drops or on the hoods. That way, you are always prepared to slow.";
car[355]="Every time you put a new tire on your bike, take the opportunity to do an otherwise overlooked but important task: Grease the quick-release and mounting-bolt threads on your car rack to prevent corrosion.";
car[356]="Joke:<br><br>Q: Why could the bike not stand up on its own?<br><br>A: It was two tyre’d.";
car[357]="\"No hour of life is lost that is spent in the saddle.\"<br><br><div class=\"SigText\">- Winston Churchill</div>";
car[358]="May your rubber side remain down and your shiny side up!";
car[359]="As tempted as you might be, don't take a day completely off the bike after the week's hardest effort. The best way to recover is with a short, easy spin - 30 to 60 minutes at a pace that always allows effortless talking.";
car[360]="How long of an event can you handle? Most cyclists can go about three times the distance (or time) of their average rides without struggling so much they risk falling to pieces.";
car[361]="Eat regularly during longer exercise. Your body can store enough energy for 90 minutes of strenuous exercise, and then you'll be running on empty. It's far better not to let yourself get to that - so don't risk bonking.";
car[362]="Biking Events: Keep an eye on your bike at events as there has been a rise in bike thefts especially at the rest stops.";
car[363]="Feeling blue? Go for a ride... four times more GP's prescribe exercise as the most common treatment for depression compared to three years ago.";
car[364]="\"Drink enough liquid throughout the day even in the cold months. You lose a lot of moisture wearing winter kit, so stay hydrated.\"<br><br><div class=\"SigText\">- Stuart Barrington</div>";
car[365]="\"The bicycle is the noblest invention of mankind.\"<br><br><div class=\"SigText\">- William Saroyan, Nobel prize winner.</div>";
car[366]="\"Buy the right bike, a mountain bike for road cycling may feel like a sensible choice, but as you get fitter and more confident its going to start to hold you back.\"<br><br><div class=\"SigText\">- Stuart Barrington</div>";
car[367]="\"Crashing is part of cycling as crying is part of love.\"<br><br><div class=\"SigText\">– Johan Museeuw</div>";